core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("home.urls", "home"), namespace="home")),
    path("accounts/", include(("accounts.urls", "accounts"), namespace="accounts")),
    path("inventory/", include(("inventory.urls", "inventory"), namespace="inventory")),
    path("reportes/", include(("reportes.urls", "reportes"), namespace="reportes")),
    path(
        "proveedores/",
        include(("proveedores.urls", "proveedores"), namespace="proveedores"),
    ),
    path("negocios/", include(("negocio.urls", "negocio"), namespace="negocio")),
    path("compras/", include(("compra.urls", "compra"), namespace="compra")),
    path(
        "navigation/",
        include(("navigation.urls", "navigation"), namespace="navigation"),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proveedores/urls.py
from django.urls import path
from .views import *

app_name = "proveedores"

urlpatterns = [
    path("", index, name="index"),
    path("add/", add, name="add"),
    path("edit/<int:pk>/", edit, name="edit"),
    path("asignar_productos/<int:pk>/", add_edit_producto, name="asignar_productos"),
]

proveedores/models.py
from django.conf import settings
from django.db import models

# from inventory.models import Producto


# Create your models here.
class Proveedor(models.Model):
    nombre = models.CharField(
        max_length=100, blank=False, null=False, verbose_name="Nombre"
    )
    numero_de_cuenta = models.CharField(
        max_length=100, blank=True, null=True, verbose_name="Número de cuenta"
    )
    opinion_de_cumplimiento = models.FileField(
        upload_to="pdf/proveedores/opiniones_de_cumplimiento/",
        blank=True,
        null=True,
        verbose_name="Opinion de cumplimiento",
    )
    razon_social = models.CharField(
        max_length=100, blank=False, null=False, verbose_name="Razón social"
    )
    rfc = models.CharField(max_length=13, blank=False, null=False, verbose_name="RFC")
    regimen_fiscal = models.ForeignKey(
        "RegimenFiscal",
        on_delete=models.PROTECT,
        null=False,
        related_name="proveedores",
        verbose_name="Régimen fiscal",
    )
    direccion = models.CharField(
        max_length=200, blank=False, null=False, verbose_name="Direccion"
    )
    codigo_postal = models.CharField(
        max_length=10, blank=False, null=False, verbose_name="Código postal"
    )
    caratula = models.FileField(
        upload_to="pdf/proveedores/caratulas/",
        blank=True,
        null=True,
        verbose_name="Caratula",
    )
    usuario_creo = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="proveedores_creados",
        verbose_name="Usuario creó",
    )
    usuario_modifico = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="proveedores_modificados",
        verbose_name="Usuario modificó",
    )
    fecha_creado = models.DateTimeField(
        auto_now_add=True, verbose_name="Fecha de creación"
    )
    fecha_modificado = models.DateTimeField(
        auto_now=True, verbose_name="Fecha de modificación"
    )
    activo = models.BooleanField(default=True, verbose_name="Activo")

    class Meta:
        verbose_name = "Proveedor"
        verbose_name_plural = "Proveedores"

    def __str__(self):
        return f"{self.razon_social} - {self.rfc}"


class ContactoProveedor(models.Model):
    proveedor = models.ForeignKey(
        Proveedor,
        on_delete=models.CASCADE,
        related_name="contactos",
        verbose_name="Proveedor",
    )
    nombre = models.CharField(
        max_length=100, blank=False, null=False, verbose_name="Nombre"
    )
    telefono = models.CharField(
        max_length=10, blank=True, null=True, verbose_name="Teléfono"
    )
    email = models.EmailField(
        max_length=100, blank=True, null=True, verbose_name="Email"
    )
    usuario_creo = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="contactos_proveedor_creados",
        verbose_name="Usuario creó",
    )
    usuario_modifico = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="contactos_proveedor_modificados",
        verbose_name="Usuario modificó",
    )
    fecha_creado = models.DateTimeField(
        auto_now_add=True, verbose_name="Fecha de creación"
    )
    fecha_modificado = models.DateTimeField(
        auto_now=True, verbose_name="Fecha de modificación"
    )
    activo = models.BooleanField(default=True, verbose_name="Activo")

    class Meta:
        verbose_name = "Contacto Proveedor"
        verbose_name_plural = "Contactos Proveedores"

    def __str__(self):
        return f"{self.nombre} - {self.proveedor.razon_social}"


class RegimenFiscal(models.Model):
    codigo = models.IntegerField(
        unique=True, blank=False, null=False, verbose_name="Código"
    )
    descripcion = models.CharField(blank=True, null=True, verbose_name="Descripción")
    activo = models.BooleanField(default=True, verbose_name="Activo")

    class Meta:
        verbose_name = "Régimen Fiscal"
        verbose_name_plural = "Régimenes Fiscales"

    def __str__(self):
        return f"{self.codigo} - {self.descripcion}"


class ProductosProveedor(models.Model):
    proveedor = models.ForeignKey(
        Proveedor,
        on_delete=models.CASCADE,
        related_name="productos",
        verbose_name="Proveedor",
    )
    producto = models.ForeignKey(
        "inventory.Producto",
        on_delete=models.CASCADE,
        related_name="productos",
        verbose_name="Producto",
    )
    precio = models.DecimalField(
        max_digits=10, decimal_places=2, blank=False, null=False, verbose_name="Precio"
    )
    usuario_creo = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="productos_proveedor_creados",
        verbose_name="Usuario creó",
    )
    usuario_modifico = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="productos_proveedor_modificados",
        verbose_name="Usuario modificó",
    )
    fecha_creado = models.DateTimeField(
        auto_now_add=True, verbose_name="Fecha de creación"
    )
    fecha_modificado = models.DateTimeField(
        auto_now=True, verbose_name="Fecha de modificación"
    )
    activo = models.BooleanField(default=True, verbose_name="Activo")

    class Meta:
        verbose_name = "Producto Proveedor"
        verbose_name_plural = "Productos Proveedores"

    def __str__(self):
        return f"{self.producto.nombre} - {self.proveedor.razon_social}"

proveedores/forms.py
from django import forms
from .models import Proveedor, ContactoProveedor, ProductosProveedor
from django.forms.widgets import ClearableFileInput
from django.forms import inlineformset_factory


class CustomClearableFileInput(ClearableFileInput):
    template_name = "forms/widgets/custom_clearable_file_input.html"


class AddProveedorForm(forms.ModelForm):
    class Meta:
        model = Proveedor
        fields = [
            "nombre",
            "razon_social",
            "rfc",
            "numero_de_cuenta",
            "regimen_fiscal",
            "codigo_postal",
            "caratula",
            "opinion_de_cumplimiento",
            "direccion",
        ]
        widgets = {
            "nombre": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Nombre del proveedor",
                    "autocomplete": "off",
                }
            ),
            "numero_de_cuenta": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Número de cuenta",
                    "autocomplete": "off",
                }
            ),
            "opinion_de_cumplimiento": CustomClearableFileInput(
                attrs={"class": "form-control"}
            ),
            "razon_social": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Razón social",
                    "autocomplete": "off",
                }
            ),
            "rfc": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "RFC",
                    "autocomplete": "off",
                }
            ),
            "regimen_fiscal": forms.Select(attrs={"class": "form-select"}),
            "direccion": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Dirección"}
            ),
            "codigo_postal": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Código postal",
                    "autocomplete": "off",
                }
            ),
            "caratula": CustomClearableFileInput(attrs={"class": "form-control"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["regimen_fiscal"].empty_label = "Selecciona un régimen fiscal"


class AddContactoProveedorForm(forms.ModelForm):
    class Meta:
        model = ContactoProveedor
        fields = ["nombre", "email", "telefono"]
        widgets = {
            "nombre": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Nombre del contacto",
                    "autocomplete": "off",
                }
            ),
            "email": forms.EmailInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Correo electrónico",
                    "autocomplete": "off",
                }
            ),
            "telefono": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Teléfono",
                    "autocomplete": "off",
                }
            ),
        }


ContactoProveedorFormSet = forms.inlineformset_factory(
    Proveedor,
    ContactoProveedor,
    form=AddContactoProveedorForm,
    extra=1,
    can_delete=True,
)


class AddProductoProveedorForm(forms.ModelForm):
    class Meta:
        model = ProductosProveedor
        fields = ["producto", "precio"]
        widgets = {
            "producto": forms.Select(attrs={"class": "form-select"}),
            "precio": forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Precio del producto",
                    "autocomplete": "off",
                }
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["producto"].empty_label = "Selecciona un producto"


ProductoProveedorFormSet = forms.inlineformset_factory(
    Proveedor,
    ProductosProveedor,
    form=AddProductoProveedorForm,
    extra=1,
    # can_delete=True,
)

proveedores/views.py
from django.shortcuts import redirect, render
from .forms import AddProveedorForm, ContactoProveedorFormSet, ProductoProveedorFormSet
from .models import Proveedor
from django.db import transaction
from django.contrib import messages


# Create your views here.
def add(request):

    if request.method == "POST":
        form = AddProveedorForm(request.POST, request.FILES)
        formset = ContactoProveedorFormSet(request.POST)
        if form.is_valid() and formset.is_valid():
            try:
                with transaction.atomic():
                    # Guardar proveedor antes de los contactos para que tenga PK
                    proveedor = form.save(commit=False)
                    proveedor.usuario_creo = request.user
                    proveedor.save()

                    contactos = formset.save(commit=False)
                    for contacto in contactos:
                        contacto.proveedor = proveedor
                        contacto.usuario_creo = request.user
                        contacto.save()

                    messages.success(request, "Proveedor guardado correctamente")
                    return redirect("proveedores:index")
            except Exception as e:
                messages.error(
                    request, f"Ha habido un problema al guardar el proveedor: {e}"
                )
        else:
            messages.error(request, "Hubo un problema al enviar el formulario.")
    else:
        form = AddProveedorForm()
        formset = ContactoProveedorFormSet()
    return render(
        request, "proveedores/add_edit.html", {"form": form, "formset": formset}
    )


def index(request):
    proveedores = Proveedor.objects.select_related("regimen_fiscal").all()
    return render(request, "proveedores/index.html", {"proveedores": list(proveedores)})


def edit(request, pk):
    proveedor = Proveedor.objects.get(pk=pk)
    contactos_iniciales = proveedor.contactos.count()

    if request.method == "POST":
        form = AddProveedorForm(request.POST, request.FILES, instance=proveedor)
        formset = ContactoProveedorFormSet(request.POST, instance=proveedor)
        if form.is_valid() and formset.is_valid():
            try:
                with transaction.atomic():
                    proveedor = form.save(commit=False)
                    proveedor.usuario_modifico = request.user
                    proveedor.save()

                    contactos = formset.save(commit=False)
                    for contacto in contactos:
                        contacto.proveedor = proveedor
                        contacto.usuario_modifico = request.user
                        contacto.save()

                    # Eliminar los objetos marcados para borrado en el formset
                    for obj in formset.deleted_objects:
                        obj.delete()

                    messages.success(request, "Proveedor actualizado correctamente")
            except Exception as e:
                messages.error(
                    request, f"Ha habido un problema al actualizar el proveedor: {e}"
                )
        else:
            messages.error(request, "Hubo un problema al enviar el formulario.")
    else:
        form = AddProveedorForm(instance=proveedor)
        formset = ContactoProveedorFormSet(instance=proveedor)
    return render(
        request,
        "proveedores/add_edit.html",
        {
            "form": form,
            "formset": formset,
            "proveedor": proveedor,
            "contactos_iniciales": contactos_iniciales,
        },
    )


def add_edit_producto(request, pk):
    proveedor = Proveedor.objects.get(pk=pk)  # Verificar que el proveedor existe
    formset = ProductoProveedorFormSet(instance=proveedor)
    productos_asignados = proveedor.productos.all()

    if request.method == "POST":
        formset = ProductoProveedorFormSet(request.POST, instance=proveedor)
        if not formset.is_valid():
            print(
                "MGMT ERR:",
                getattr(formset, "management_form", None)
                and formset.management_form.errors,
            )
            print("NON_FORM:", formset.non_form_errors())
            for i, f in enumerate(formset.forms):
                print(f"Form {i} errors:", f.errors)
        if formset.is_valid():
            try:
                with transaction.atomic():
                    productos = formset.save(commit=False)
                    for producto in productos:
                        # producto.proveedor = proveedor
                        if not producto.pk:
                            producto.usuario_creo = request.user
                        else:
                            producto.usuario_modifico = request.user
                        producto.save()

                    messages.success(
                        request, "Productos del proveedor actualizados correctamente"
                    )
                    return redirect("proveedores:index")
            except Exception as e:
                messages.error(
                    request,
                    f"Ha habido un problema al actualizar los productos del proveedor: {e}",
                )
        else:
            messages.error(request, "Hubo un problema al enviar el formulario.")
    return render(
        request,
        "proveedores/add_edit_producto.html",
        {"formset": formset, "productos": productos_asignados, "proveedor": proveedor},
    )

proveedores/templates/proveedores/add_edit.html
{% extends "templates/layout.html" %}
{% load static %}
{% block title %}
Proveedores
{% endblock title %}
{% block body %}
<script src="{% static 'js/proveedores/add_edit.js' %}"></script>
<script>
  const contactosIniciales = {{ contactosIniciales|default:0 }};
</script>
  <div class="container">
    <h2 class="mb-3">
      {% if proveedor %}
        Edición de Proveedor
      {% else %}
        Alta de Proveedor
      {% endif %}
    </h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <section class="row">
        <div class="col-lg-6 col-12 mb-3">
          {{ form.nombre.label_tag }}
          {{ form.nombre }}
        </div>
        <div class="col-lg-6 col-12 mb-3">
          {{ form.razon_social.label_tag }}
          {{ form.razon_social }}
        </div>
        <div class="col-lg-6 col-12 mb-3">
          {{ form.rfc.label_tag }}
          {{ form.rfc }}
        </div>
        <div class="col-lg-6 col-12 mb-3">
          {{ form.numero_de_cuenta.label_tag }}
          {{ form.numero_de_cuenta }}
        </div>
        <div class="col-12 mb-3">
          {{ form.regimen_fiscal.label_tag }}
          {{ form.regimen_fiscal }}
        </div>
        <div class="col-lg-4 col-12 mb-3">
          {{ form.codigo_postal.label_tag }}
          {{ form.codigo_postal }}
        </div>
        <div class="col-lg-4 col-12 mb-3">
          {{ form.caratula.label_tag }}
          {{ form.caratula }}
        </div>
        <div class="col-lg-4 col-12 mb-3">
          {{ form.opinion_de_cumplimiento.label_tag }}
          {{ form.opinion_de_cumplimiento }}
        </div>
        <div class="col-12 mb-3">
          {{ form.direccion.label_tag }}
          {{ form.direccion }}
        </div>
      </section>
      <h4>Contactos</h4>
      {{ formset.management_form }}
      <section id="contContactos" class="row">
        {% for form in formset %}
        <div class="contacto-form row">
          <h5 class="title-contacto">Contacto #{{ forloop.counter }}</h5>
          <div class="col-lg-4 col-12 mb-3">
            {{ form.nombre.label_tag }}
            {{ form.nombre }}
          </div>
          <div class="col-lg-4 col-12 mb-3">
            {{ form.email.label_tag }}
            {{ form.email }}
          </div>
          <div class="col-lg-4 col-12 mb-3">
            {{ form.telefono.label_tag }}
            {{ form.telefono }}
          </div>
        </div>
        {% endfor %}
      </section>
      <section class="mb-3 d-flex gap-2">
        <button type="button" class="btn btn-secondary col-6" id="addContacto">Añadir Contacto</button>
        <button type="button" class="btn btn-danger col-6" id="deleteContacto" disabled>Borrar Contacto</button>
      </section>
      <button type="submit" class="btn btn-primary w-100">Guardar</button>
    </form>
  </div>
{% endblock body %}

proveedores/templates/proveedores/add_edit_producto.html
{% extends "templates/layout.html" %}
{% block title %}
  {% if form.intance.pk %}
    Editar Productos
  {% else %}
    Asignar Productos
  {% endif %}
{% endblock title %}
{% block body %}
  <div class="container">
    <h2>Asignar Productos al Proveedor {{ proveedor.nombre }}</h2>
    <form method="post">
      {% csrf_token %}
      {{ formset.management_form }}
      <section id="contProductos" class="row">
        {% for form in formset %}
          {{ form.id }}
          <h5>Producto {{ forloop.counter }}</h5>
          <div class="col-12 col-lg-6 mb-3">{{ form.producto.label_tag }} {{ form.producto }}</div>
          <div class="col-12 col-lg-6 mb-3">{{ form.precio.label_tag }} {{ form.precio }}</div>
        {% endfor %}
      </section>
      <section class="mb-3 row">
        <div class="col-12 col-lg-6">
          <button type="button" class="btn btn-secondary w-100" id="addProducto">Añadir Producto</button>
        </div>
        <div class="col-12 col-lg-6">
          <button type="button"
                  class="btn btn-danger w-100"
                  id="deleteProducto"
                  disabled>Borrar Producto</button>
        </section>
        <div class="col-12">
          <button type="submit" class="btn btn-primary w-100">Asignar Productos</button>
        </div>
      </div>
    </form>
  </div>
{% endblock body %}

proveedores/templates/proveedores/index.html
{% extends "templates/layout.html" %}
{% load static %}
{% block title %}
    Proveedores
{% endblock title %}
{% block body %}
    <script src="{% static 'js/proveedores/index.js' %}"></script>
    <script>const proveedores = {{ proveedores|safe }}</script>
    <div class="container">
        <h2>Lista de Proveedores</h2>
        <a class="btn btn-primary" href="{% url 'proveedores:add' %}">Añadir Proveedor</a>
        <section id="tablaProveedores">
            <table id="myTable" class="table table-hover table-sm">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Razón Social</th>
                        <th>RFC</th>
                        <th>No. Cuenta</th>
                        <th>Régimen Fiscal</th>
                        <th>Código Postal</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for proveedor in proveedores %}
                        <tr>
                            <td>{{ proveedor.id }}</td>
                            <td>{{ proveedor.nombre }}</td>
                            <td>{{ proveedor.razon_social }}</td>
                            <td>{{ proveedor.rfc }}</td>
                            <td>{{ proveedor.numero_de_cuenta }}</td>
                            <td>{{ proveedor.regimen_fiscal }}</td>
                            <td>{{ proveedor.codigo_postal }}</td>
                            <td>
                                <div class="d-flex gap-2">
                                    <a href="{% url 'proveedores:edit' proveedor.id %}"
                                       title="Editar Proveedor"><i class="fa-solid fa-pen-to-square"></i></a>
                                    <a href="{% url 'proveedores:asignar_productos' proveedor.id %}"
                                       title="Asignar Productos"><i class="fa-solid fa-plus-minus"></i></a>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </section>
    </div>
{% endblock body %}